spring:
  application:
    name: FSneakers

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=FSneakers;encrypt=true;trustServerCertificate=true
    username: sa
    password: 28102003
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  output:
    ansi:
      enabled: ALWAYS

  web:
    resources:
      static-locations: classpath:/static/

  config:
    import: optional:file:.env[.properties]

  devtools:
    restart:
      enabled: false

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

cloudinary:
  cloud-name: your_cloud_name
  api-key: your_api_key
  api-secret: your_api_secret

#server:
#  port: 8081
