spring:
  application:
    name: FSneakers

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=FSneakers;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  output:
    ansi:
      enabled: ALWAYS

  web:
    resources:
      static-locations: classpath:/static/

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect

cloudinary:
  cloud-name: drtrpwvpc
  api-key: 914935546269538
  api-secret: hI2kdum0LWtvISeM6_jj18SGJdc

server:
  port: 8081
