
spring:
  application:
    name: FSneakers
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=FSneakers;encrypt=true;trustServerCertificate=true
    username: sa
    password: 28102003
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
